/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CommunityFilter {
    city?: string;
    category?: CommunityCategory;
    college?: string;
}
export interface Listing {
    id: bigint;
    status: ListingStatus;
    title: string;
    sellerPrincipal: Principal;
    city: string;
    createdAt: bigint;
    description: string;
    listingType: ListingType;
    sellerName: string;
    areaScope: ListingAreaScope;
    category: ListingCategory;
    image?: ExternalBlob;
    price: number;
    college: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EventFilter {
    city?: string;
    organizerType?: EventOrganizerType;
    category?: EventCategory;
    college?: string;
}
export interface Event {
    id: bigint;
    organizer: string;
    title: string;
    venue: string;
    city: string;
    createdAt: bigint;
    description: string;
    organizerType: EventOrganizerType;
    attendees: Array<Principal>;
    category: EventCategory;
    image?: ExternalBlob;
    registrationLink?: string;
    college: string;
    eventDate: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Community {
    id: bigint;
    members: Array<Principal>;
    city: string;
    name: string;
    createdAt: bigint;
    description: string;
    coverImage?: ExternalBlob;
    pendingRequests: Array<Principal>;
    creatorPrincipal: Principal;
    category: CommunityCategory;
    isPublic: boolean;
    college: string;
}
export interface ListingFilter {
    city?: string;
    listingType?: ListingType;
    areaScope?: ListingAreaScope;
    category?: ListingCategory;
    college?: string;
}
export interface Message {
    id: string;
    text: string;
    conversationId: string;
    senderPrincipal: Principal;
    timestamp: bigint;
}
export interface Conversation {
    id: string;
    participants: Array<Principal>;
    createdAt: bigint;
}
export interface UserProfile {
    city: string;
    profileImage?: ExternalBlob;
    name: string;
    interestAreas: Array<string>;
    otherSocialUrl?: string;
    course: string;
    yearOfStudy: string;
    linkedinUrl?: string;
    college: string;
}
export enum CommunityCategory {
    other = "other",
    marketing = "marketing",
    design = "design",
    entrepreneurship = "entrepreneurship",
    coding = "coding",
    science = "science"
}
export enum EventCategory {
    workshop = "workshop",
    other = "other",
    tech = "tech",
    cultural = "cultural",
    business = "business",
    sports = "sports"
}
export enum EventOrganizerType {
    user = "user",
    platform = "platform"
}
export enum ListingAreaScope {
    all = "all",
    city = "city",
    campus = "campus"
}
export enum ListingCategory {
    all = "all",
    other = "other",
    notes = "notes",
    stationery = "stationery",
    books = "books"
}
export enum ListingStatus {
    rented = "rented",
    active = "active",
    sold = "sold"
}
export enum ListingType {
    buy = "buy",
    rent = "rent",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMember(communityId: bigint, member: Principal): Promise<void>;
    approveMember(communityId: bigint, member: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCommunity(name: string, description: string, category: CommunityCategory, college: string, city: string, isPublic: boolean, coverImage: ExternalBlob | null): Promise<bigint>;
    createEvent(title: string, description: string, category: EventCategory, organizer: string, organizerType: EventOrganizerType, college: string, city: string, venue: string, eventDate: bigint, registrationLink: string | null, image: ExternalBlob | null): Promise<bigint>;
    createListing(title: string, description: string, category: ListingCategory, listingType: ListingType, price: number, sellerName: string, college: string, city: string, areaScope: ListingAreaScope, image: ExternalBlob | null): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunities(filter: CommunityFilter | null): Promise<Array<Community>>;
    getCommunityById(id: bigint): Promise<Community | null>;
    getConversations(): Promise<Array<Conversation>>;
    getEventById(id: bigint): Promise<Event | null>;
    getEvents(filter: EventFilter | null): Promise<Array<Event>>;
    getListingById(id: bigint): Promise<Listing | null>;
    getListings(filter: ListingFilter | null): Promise<Array<Listing>>;
    getMessages(conversationId: string): Promise<Array<Message>>;
    getMyCommunities(): Promise<Array<Community>>;
    getPlatformEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerForEvent(eventId: bigint): Promise<void>;
    requestToJoin(communityId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(conversationId: string, text: string): Promise<void>;
    startConversation(otherPrincipal: Principal): Promise<Conversation>;
    updateListingStatus(id: bigint, status: ListingStatus): Promise<void>;
    uploadProfileImage(image: ExternalBlob): Promise<void>;
}
import type { Community as _Community, CommunityCategory as _CommunityCategory, CommunityFilter as _CommunityFilter, Event as _Event, EventCategory as _EventCategory, EventFilter as _EventFilter, EventOrganizerType as _EventOrganizerType, ExternalBlob as _ExternalBlob, Listing as _Listing, ListingAreaScope as _ListingAreaScope, ListingCategory as _ListingCategory, ListingFilter as _ListingFilter, ListingStatus as _ListingStatus, ListingType as _ListingType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1);
            return result;
        }
    }
    async approveMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMember(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCommunity(arg0: string, arg1: string, arg2: CommunityCategory, arg3: string, arg4: string, arg5: boolean, arg6: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunity(arg0, arg1, to_candid_CommunityCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunity(arg0, arg1, to_candid_CommunityCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: EventCategory, arg3: string, arg4: EventOrganizerType, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: string | null, arg10: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, to_candid_EventCategory_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_EventOrganizerType_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg9), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, to_candid_EventCategory_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_EventOrganizerType_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg9), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: ListingCategory, arg3: ListingType, arg4: number, arg5: string, arg6: string, arg7: string, arg8: ListingAreaScope, arg9: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n19(this._uploadFile, this._downloadFile, arg2), to_candid_ListingType_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_ListingAreaScope_n23(this._uploadFile, this._downloadFile, arg8), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n19(this._uploadFile, this._downloadFile, arg2), to_candid_ListingType_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_ListingAreaScope_n23(this._uploadFile, this._downloadFile, arg8), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunities(arg0: CommunityFilter | null): Promise<Array<Community>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunities(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunities(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityById(arg0: bigint): Promise<Community | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityById(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityById(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getEventById(arg0: bigint): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(arg0: EventFilter | null): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(arg0: ListingFilter | null): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyCommunities(): Promise<Array<Community>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCommunities();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCommunities();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformEvents();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformEvents();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerForEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(arg0);
            return result;
        }
    }
    async requestToJoin(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestToJoin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestToJoin(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startConversation(arg0: Principal): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0);
            return result;
        }
    }
    async updateListingStatus(arg0: bigint, arg1: ListingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingStatus(arg0, to_candid_ListingStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingStatus(arg0, to_candid_ListingStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadProfileImage(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfileImage(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfileImage(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CommunityCategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityCategory): CommunityCategory {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Community_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Community): Promise<Community> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_EventCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_EventOrganizerType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventOrganizerType): EventOrganizerType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingAreaScope_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingAreaScope): ListingAreaScope {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ListingCategory_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCategory): ListingCategory {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ListingType_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingType): ListingType {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Community]): Promise<Community | null> {
    return value.length === 0 ? null : await from_candid_Community_n37(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Promise<Event | null> {
    return value.length === 0 ? null : await from_candid_Event_n43(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    profileImage: [] | [_ExternalBlob];
    name: string;
    interestAreas: Array<string>;
    otherSocialUrl: [] | [string];
    course: string;
    yearOfStudy: string;
    linkedinUrl: [] | [string];
    college: string;
}): Promise<{
    city: string;
    profileImage?: ExternalBlob;
    name: string;
    interestAreas: Array<string>;
    otherSocialUrl?: string;
    course: string;
    yearOfStudy: string;
    linkedinUrl?: string;
    college: string;
}> {
    return {
        city: value.city,
        profileImage: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        interestAreas: value.interestAreas,
        otherSocialUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.otherSocialUrl)),
        course: value.course,
        yearOfStudy: value.yearOfStudy,
        linkedinUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.linkedinUrl)),
        college: value.college
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<Principal>;
    city: string;
    name: string;
    createdAt: bigint;
    description: string;
    coverImage: [] | [_ExternalBlob];
    pendingRequests: Array<Principal>;
    creatorPrincipal: Principal;
    category: _CommunityCategory;
    isPublic: boolean;
    college: string;
}): Promise<{
    id: bigint;
    members: Array<Principal>;
    city: string;
    name: string;
    createdAt: bigint;
    description: string;
    coverImage?: ExternalBlob;
    pendingRequests: Array<Principal>;
    creatorPrincipal: Principal;
    category: CommunityCategory;
    isPublic: boolean;
    college: string;
}> {
    return {
        id: value.id,
        members: value.members,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        coverImage: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.coverImage)),
        pendingRequests: value.pendingRequests,
        creatorPrincipal: value.creatorPrincipal,
        category: from_candid_CommunityCategory_n39(_uploadFile, _downloadFile, value.category),
        isPublic: value.isPublic,
        college: value.college
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    organizer: string;
    title: string;
    venue: string;
    city: string;
    createdAt: bigint;
    description: string;
    organizerType: _EventOrganizerType;
    attendees: Array<Principal>;
    category: _EventCategory;
    image: [] | [_ExternalBlob];
    registrationLink: [] | [string];
    college: string;
    eventDate: bigint;
}): Promise<{
    id: bigint;
    organizer: string;
    title: string;
    venue: string;
    city: string;
    createdAt: bigint;
    description: string;
    organizerType: EventOrganizerType;
    attendees: Array<Principal>;
    category: EventCategory;
    image?: ExternalBlob;
    registrationLink?: string;
    college: string;
    eventDate: bigint;
}> {
    return {
        id: value.id,
        organizer: value.organizer,
        title: value.title,
        venue: value.venue,
        city: value.city,
        createdAt: value.createdAt,
        description: value.description,
        organizerType: from_candid_EventOrganizerType_n45(_uploadFile, _downloadFile, value.organizerType),
        attendees: value.attendees,
        category: from_candid_EventCategory_n47(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.image)),
        registrationLink: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.registrationLink)),
        college: value.college,
        eventDate: value.eventDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    title: string;
    sellerPrincipal: Principal;
    city: string;
    createdAt: bigint;
    description: string;
    listingType: _ListingType;
    sellerName: string;
    areaScope: _ListingAreaScope;
    category: _ListingCategory;
    image: [] | [_ExternalBlob];
    price: number;
    college: string;
}): Promise<{
    id: bigint;
    status: ListingStatus;
    title: string;
    sellerPrincipal: Principal;
    city: string;
    createdAt: bigint;
    description: string;
    listingType: ListingType;
    sellerName: string;
    areaScope: ListingAreaScope;
    category: ListingCategory;
    image?: ExternalBlob;
    price: number;
    college: string;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n56(_uploadFile, _downloadFile, value.status),
        title: value.title,
        sellerPrincipal: value.sellerPrincipal,
        city: value.city,
        createdAt: value.createdAt,
        description: value.description,
        listingType: from_candid_ListingType_n58(_uploadFile, _downloadFile, value.listingType),
        sellerName: value.sellerName,
        areaScope: from_candid_ListingAreaScope_n60(_uploadFile, _downloadFile, value.areaScope),
        category: from_candid_ListingCategory_n62(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.image)),
        price: value.price,
        college: value.college
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    marketing: null;
} | {
    design: null;
} | {
    entrepreneurship: null;
} | {
    coding: null;
} | {
    science: null;
}): CommunityCategory {
    return "other" in value ? CommunityCategory.other : "marketing" in value ? CommunityCategory.marketing : "design" in value ? CommunityCategory.design : "entrepreneurship" in value ? CommunityCategory.entrepreneurship : "coding" in value ? CommunityCategory.coding : "science" in value ? CommunityCategory.science : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    platform: null;
}): EventOrganizerType {
    return "user" in value ? EventOrganizerType.user : "platform" in value ? EventOrganizerType.platform : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workshop: null;
} | {
    other: null;
} | {
    tech: null;
} | {
    cultural: null;
} | {
    business: null;
} | {
    sports: null;
}): EventCategory {
    return "workshop" in value ? EventCategory.workshop : "other" in value ? EventCategory.other : "tech" in value ? EventCategory.tech : "cultural" in value ? EventCategory.cultural : "business" in value ? EventCategory.business : "sports" in value ? EventCategory.sports : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
}): ListingStatus {
    return "rented" in value ? ListingStatus.rented : "active" in value ? ListingStatus.active : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    rent: null;
} | {
    sell: null;
}): ListingType {
    return "buy" in value ? ListingType.buy : "rent" in value ? ListingType.rent : "sell" in value ? ListingType.sell : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    city: null;
} | {
    campus: null;
}): ListingAreaScope {
    return "all" in value ? ListingAreaScope.all : "city" in value ? ListingAreaScope.city : "campus" in value ? ListingAreaScope.campus : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    other: null;
} | {
    notes: null;
} | {
    stationery: null;
} | {
    books: null;
}): ListingCategory {
    return "all" in value ? ListingCategory.all : "other" in value ? ListingCategory.other : "notes" in value ? ListingCategory.notes : "stationery" in value ? ListingCategory.stationery : "books" in value ? ListingCategory.books : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Community>): Promise<Array<Community>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Community_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n43(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n54(_uploadFile, _downloadFile, x)));
}
function to_candid_CommunityCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityCategory): _CommunityCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CommunityFilter_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityFilter): _CommunityFilter {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_EventCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_EventFilter_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter): _EventFilter {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_EventOrganizerType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventOrganizerType): _EventOrganizerType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingAreaScope_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingAreaScope): _ListingAreaScope {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ListingCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): _ListingCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilter_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter): _ListingFilter {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ListingType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): _ListingType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityFilter | null): [] | [_CommunityFilter] {
    return value === null ? candid_none() : candid_some(to_candid_CommunityFilter_n34(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter | null): [] | [_EventFilter] {
    return value === null ? candid_none() : candid_some(to_candid_EventFilter_n50(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter | null): [] | [_ListingFilter] {
    return value === null ? candid_none() : candid_some(to_candid_ListingFilter_n65(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    category?: CommunityCategory;
    college?: string;
}): {
    city: [] | [string];
    category: [] | [_CommunityCategory];
    college: [] | [string];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        category: value.category ? candid_some(to_candid_CommunityCategory_n10(_uploadFile, _downloadFile, value.category)) : candid_none(),
        college: value.college ? candid_some(value.college) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    organizerType?: EventOrganizerType;
    category?: EventCategory;
    college?: string;
}): {
    city: [] | [string];
    organizerType: [] | [_EventOrganizerType];
    category: [] | [_EventCategory];
    college: [] | [string];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        organizerType: value.organizerType ? candid_some(to_candid_EventOrganizerType_n16(_uploadFile, _downloadFile, value.organizerType)) : candid_none(),
        category: value.category ? candid_some(to_candid_EventCategory_n14(_uploadFile, _downloadFile, value.category)) : candid_none(),
        college: value.college ? candid_some(value.college) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    listingType?: ListingType;
    areaScope?: ListingAreaScope;
    category?: ListingCategory;
    college?: string;
}): {
    city: [] | [string];
    listingType: [] | [_ListingType];
    areaScope: [] | [_ListingAreaScope];
    category: [] | [_ListingCategory];
    college: [] | [string];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        listingType: value.listingType ? candid_some(to_candid_ListingType_n21(_uploadFile, _downloadFile, value.listingType)) : candid_none(),
        areaScope: value.areaScope ? candid_some(to_candid_ListingAreaScope_n23(_uploadFile, _downloadFile, value.areaScope)) : candid_none(),
        category: value.category ? candid_some(to_candid_ListingCategory_n19(_uploadFile, _downloadFile, value.category)) : candid_none(),
        college: value.college ? candid_some(value.college) : candid_none()
    };
}
async function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    profileImage?: ExternalBlob;
    name: string;
    interestAreas: Array<string>;
    otherSocialUrl?: string;
    course: string;
    yearOfStudy: string;
    linkedinUrl?: string;
    college: string;
}): Promise<{
    city: string;
    profileImage: [] | [_ExternalBlob];
    name: string;
    interestAreas: Array<string>;
    otherSocialUrl: [] | [string];
    course: string;
    yearOfStudy: string;
    linkedinUrl: [] | [string];
    college: string;
}> {
    return {
        city: value.city,
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.profileImage)) : candid_none(),
        name: value.name,
        interestAreas: value.interestAreas,
        otherSocialUrl: value.otherSocialUrl ? candid_some(value.otherSocialUrl) : candid_none(),
        course: value.course,
        yearOfStudy: value.yearOfStudy,
        linkedinUrl: value.linkedinUrl ? candid_some(value.linkedinUrl) : candid_none(),
        college: value.college
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityCategory): {
    other: null;
} | {
    marketing: null;
} | {
    design: null;
} | {
    entrepreneurship: null;
} | {
    coding: null;
} | {
    science: null;
} {
    return value == CommunityCategory.other ? {
        other: null
    } : value == CommunityCategory.marketing ? {
        marketing: null
    } : value == CommunityCategory.design ? {
        design: null
    } : value == CommunityCategory.entrepreneurship ? {
        entrepreneurship: null
    } : value == CommunityCategory.coding ? {
        coding: null
    } : value == CommunityCategory.science ? {
        science: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    workshop: null;
} | {
    other: null;
} | {
    tech: null;
} | {
    cultural: null;
} | {
    business: null;
} | {
    sports: null;
} {
    return value == EventCategory.workshop ? {
        workshop: null
    } : value == EventCategory.other ? {
        other: null
    } : value == EventCategory.tech ? {
        tech: null
    } : value == EventCategory.cultural ? {
        cultural: null
    } : value == EventCategory.business ? {
        business: null
    } : value == EventCategory.sports ? {
        sports: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventOrganizerType): {
    user: null;
} | {
    platform: null;
} {
    return value == EventOrganizerType.user ? {
        user: null
    } : value == EventOrganizerType.platform ? {
        platform: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): {
    all: null;
} | {
    other: null;
} | {
    notes: null;
} | {
    stationery: null;
} | {
    books: null;
} {
    return value == ListingCategory.all ? {
        all: null
    } : value == ListingCategory.other ? {
        other: null
    } : value == ListingCategory.notes ? {
        notes: null
    } : value == ListingCategory.stationery ? {
        stationery: null
    } : value == ListingCategory.books ? {
        books: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): {
    buy: null;
} | {
    rent: null;
} | {
    sell: null;
} {
    return value == ListingType.buy ? {
        buy: null
    } : value == ListingType.rent ? {
        rent: null
    } : value == ListingType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingAreaScope): {
    all: null;
} | {
    city: null;
} | {
    campus: null;
} {
    return value == ListingAreaScope.all ? {
        all: null
    } : value == ListingAreaScope.city ? {
        city: null
    } : value == ListingAreaScope.campus ? {
        campus: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
} {
    return value == ListingStatus.rented ? {
        rented: null
    } : value == ListingStatus.active ? {
        active: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
