/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Community {
  'id' : bigint,
  'members' : Array<Principal>,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'coverImage' : [] | [ExternalBlob],
  'pendingRequests' : Array<Principal>,
  'creatorPrincipal' : Principal,
  'category' : CommunityCategory,
  'isPublic' : boolean,
  'college' : string,
}
export type CommunityCategory = { 'other' : null } |
  { 'marketing' : null } |
  { 'design' : null } |
  { 'entrepreneurship' : null } |
  { 'coding' : null } |
  { 'science' : null };
export interface CommunityFilter {
  'city' : [] | [string],
  'category' : [] | [CommunityCategory],
  'college' : [] | [string],
}
export interface Conversation {
  'id' : string,
  'participants' : Array<Principal>,
  'createdAt' : bigint,
}
export interface Event {
  'id' : bigint,
  'organizer' : string,
  'title' : string,
  'venue' : string,
  'city' : string,
  'createdAt' : bigint,
  'description' : string,
  'organizerType' : EventOrganizerType,
  'attendees' : Array<Principal>,
  'category' : EventCategory,
  'image' : [] | [ExternalBlob],
  'registrationLink' : [] | [string],
  'college' : string,
  'eventDate' : bigint,
}
export type EventCategory = { 'workshop' : null } |
  { 'other' : null } |
  { 'tech' : null } |
  { 'cultural' : null } |
  { 'business' : null } |
  { 'sports' : null };
export interface EventFilter {
  'city' : [] | [string],
  'organizerType' : [] | [EventOrganizerType],
  'category' : [] | [EventCategory],
  'college' : [] | [string],
}
export type EventOrganizerType = { 'user' : null } |
  { 'platform' : null };
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'sellerPrincipal' : Principal,
  'city' : string,
  'createdAt' : bigint,
  'description' : string,
  'listingType' : ListingType,
  'sellerName' : string,
  'areaScope' : ListingAreaScope,
  'category' : ListingCategory,
  'image' : [] | [ExternalBlob],
  'price' : number,
  'college' : string,
}
export type ListingAreaScope = { 'all' : null } |
  { 'city' : null } |
  { 'campus' : null };
export type ListingCategory = { 'all' : null } |
  { 'other' : null } |
  { 'notes' : null } |
  { 'stationery' : null } |
  { 'books' : null };
export interface ListingFilter {
  'city' : [] | [string],
  'listingType' : [] | [ListingType],
  'areaScope' : [] | [ListingAreaScope],
  'category' : [] | [ListingCategory],
  'college' : [] | [string],
}
export type ListingStatus = { 'rented' : null } |
  { 'active' : null } |
  { 'sold' : null };
export type ListingType = { 'buy' : null } |
  { 'rent' : null } |
  { 'sell' : null };
export interface Message {
  'id' : string,
  'text' : string,
  'conversationId' : string,
  'senderPrincipal' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile {
  'city' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'interestAreas' : Array<string>,
  'otherSocialUrl' : [] | [string],
  'course' : string,
  'yearOfStudy' : string,
  'linkedinUrl' : [] | [string],
  'college' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[bigint, Principal], undefined>,
  'approveMember' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunity' : ActorMethod<
    [
      string,
      string,
      CommunityCategory,
      string,
      string,
      boolean,
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'createEvent' : ActorMethod<
    [
      string,
      string,
      EventCategory,
      string,
      EventOrganizerType,
      string,
      string,
      string,
      bigint,
      [] | [string],
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'createListing' : ActorMethod<
    [
      string,
      string,
      ListingCategory,
      ListingType,
      number,
      string,
      string,
      string,
      ListingAreaScope,
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunities' : ActorMethod<[[] | [CommunityFilter]], Array<Community>>,
  'getCommunityById' : ActorMethod<[bigint], [] | [Community]>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getEventById' : ActorMethod<[bigint], [] | [Event]>,
  'getEvents' : ActorMethod<[[] | [EventFilter]], Array<Event>>,
  'getListingById' : ActorMethod<[bigint], [] | [Listing]>,
  'getListings' : ActorMethod<[[] | [ListingFilter]], Array<Listing>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMyCommunities' : ActorMethod<[], Array<Community>>,
  'getPlatformEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForEvent' : ActorMethod<[bigint], undefined>,
  'requestToJoin' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'startConversation' : ActorMethod<[Principal], Conversation>,
  'updateListingStatus' : ActorMethod<[bigint, ListingStatus], undefined>,
  'uploadProfileImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];