/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityCategory = IDL.Variant({
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'design' : IDL.Null,
  'entrepreneurship' : IDL.Null,
  'coding' : IDL.Null,
  'science' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EventCategory = IDL.Variant({
  'workshop' : IDL.Null,
  'other' : IDL.Null,
  'tech' : IDL.Null,
  'cultural' : IDL.Null,
  'business' : IDL.Null,
  'sports' : IDL.Null,
});
export const EventOrganizerType = IDL.Variant({
  'user' : IDL.Null,
  'platform' : IDL.Null,
});
export const ListingCategory = IDL.Variant({
  'all' : IDL.Null,
  'other' : IDL.Null,
  'notes' : IDL.Null,
  'stationery' : IDL.Null,
  'books' : IDL.Null,
});
export const ListingType = IDL.Variant({
  'buy' : IDL.Null,
  'rent' : IDL.Null,
  'sell' : IDL.Null,
});
export const ListingAreaScope = IDL.Variant({
  'all' : IDL.Null,
  'city' : IDL.Null,
  'campus' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'interestAreas' : IDL.Vec(IDL.Text),
  'otherSocialUrl' : IDL.Opt(IDL.Text),
  'course' : IDL.Text,
  'yearOfStudy' : IDL.Text,
  'linkedinUrl' : IDL.Opt(IDL.Text),
  'college' : IDL.Text,
});
export const CommunityFilter = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(CommunityCategory),
  'college' : IDL.Opt(IDL.Text),
});
export const Community = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(IDL.Principal),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'pendingRequests' : IDL.Vec(IDL.Principal),
  'creatorPrincipal' : IDL.Principal,
  'category' : CommunityCategory,
  'isPublic' : IDL.Bool,
  'college' : IDL.Text,
});
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : IDL.Int,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'organizer' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'organizerType' : EventOrganizerType,
  'attendees' : IDL.Vec(IDL.Principal),
  'category' : EventCategory,
  'image' : IDL.Opt(ExternalBlob),
  'registrationLink' : IDL.Opt(IDL.Text),
  'college' : IDL.Text,
  'eventDate' : IDL.Int,
});
export const EventFilter = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'organizerType' : IDL.Opt(EventOrganizerType),
  'category' : IDL.Opt(EventCategory),
  'college' : IDL.Opt(IDL.Text),
});
export const ListingStatus = IDL.Variant({
  'rented' : IDL.Null,
  'active' : IDL.Null,
  'sold' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'sellerPrincipal' : IDL.Principal,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'listingType' : ListingType,
  'sellerName' : IDL.Text,
  'areaScope' : ListingAreaScope,
  'category' : ListingCategory,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Float64,
  'college' : IDL.Text,
});
export const ListingFilter = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'listingType' : IDL.Opt(ListingType),
  'areaScope' : IDL.Opt(ListingAreaScope),
  'category' : IDL.Opt(ListingCategory),
  'college' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'conversationId' : IDL.Text,
  'senderPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'approveMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunity' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CommunityCategory,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        EventCategory,
        IDL.Text,
        EventOrganizerType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ListingCategory,
        ListingType,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ListingAreaScope,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunities' : IDL.Func(
      [IDL.Opt(CommunityFilter)],
      [IDL.Vec(Community)],
      ['query'],
    ),
  'getCommunityById' : IDL.Func([IDL.Nat], [IDL.Opt(Community)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getEventById' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getEvents' : IDL.Func([IDL.Opt(EventFilter)], [IDL.Vec(Event)], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListings' : IDL.Func(
      [IDL.Opt(ListingFilter)],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMyCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'getPlatformEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForEvent' : IDL.Func([IDL.Nat], [], []),
  'requestToJoin' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startConversation' : IDL.Func([IDL.Principal], [Conversation], []),
  'updateListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
  'uploadProfileImage' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityCategory = IDL.Variant({
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'design' : IDL.Null,
    'entrepreneurship' : IDL.Null,
    'coding' : IDL.Null,
    'science' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EventCategory = IDL.Variant({
    'workshop' : IDL.Null,
    'other' : IDL.Null,
    'tech' : IDL.Null,
    'cultural' : IDL.Null,
    'business' : IDL.Null,
    'sports' : IDL.Null,
  });
  const EventOrganizerType = IDL.Variant({
    'user' : IDL.Null,
    'platform' : IDL.Null,
  });
  const ListingCategory = IDL.Variant({
    'all' : IDL.Null,
    'other' : IDL.Null,
    'notes' : IDL.Null,
    'stationery' : IDL.Null,
    'books' : IDL.Null,
  });
  const ListingType = IDL.Variant({
    'buy' : IDL.Null,
    'rent' : IDL.Null,
    'sell' : IDL.Null,
  });
  const ListingAreaScope = IDL.Variant({
    'all' : IDL.Null,
    'city' : IDL.Null,
    'campus' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'interestAreas' : IDL.Vec(IDL.Text),
    'otherSocialUrl' : IDL.Opt(IDL.Text),
    'course' : IDL.Text,
    'yearOfStudy' : IDL.Text,
    'linkedinUrl' : IDL.Opt(IDL.Text),
    'college' : IDL.Text,
  });
  const CommunityFilter = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(CommunityCategory),
    'college' : IDL.Opt(IDL.Text),
  });
  const Community = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(IDL.Principal),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'pendingRequests' : IDL.Vec(IDL.Principal),
    'creatorPrincipal' : IDL.Principal,
    'category' : CommunityCategory,
    'isPublic' : IDL.Bool,
    'college' : IDL.Text,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : IDL.Int,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'organizer' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'organizerType' : EventOrganizerType,
    'attendees' : IDL.Vec(IDL.Principal),
    'category' : EventCategory,
    'image' : IDL.Opt(ExternalBlob),
    'registrationLink' : IDL.Opt(IDL.Text),
    'college' : IDL.Text,
    'eventDate' : IDL.Int,
  });
  const EventFilter = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'organizerType' : IDL.Opt(EventOrganizerType),
    'category' : IDL.Opt(EventCategory),
    'college' : IDL.Opt(IDL.Text),
  });
  const ListingStatus = IDL.Variant({
    'rented' : IDL.Null,
    'active' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'sellerPrincipal' : IDL.Principal,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'listingType' : ListingType,
    'sellerName' : IDL.Text,
    'areaScope' : ListingAreaScope,
    'category' : ListingCategory,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Float64,
    'college' : IDL.Text,
  });
  const ListingFilter = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'listingType' : IDL.Opt(ListingType),
    'areaScope' : IDL.Opt(ListingAreaScope),
    'category' : IDL.Opt(ListingCategory),
    'college' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'conversationId' : IDL.Text,
    'senderPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'approveMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunity' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CommunityCategory,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          EventCategory,
          IDL.Text,
          EventOrganizerType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ListingCategory,
          ListingType,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ListingAreaScope,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunities' : IDL.Func(
        [IDL.Opt(CommunityFilter)],
        [IDL.Vec(Community)],
        ['query'],
      ),
    'getCommunityById' : IDL.Func([IDL.Nat], [IDL.Opt(Community)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getEventById' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getEvents' : IDL.Func([IDL.Opt(EventFilter)], [IDL.Vec(Event)], ['query']),
    'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListings' : IDL.Func(
        [IDL.Opt(ListingFilter)],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMyCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'getPlatformEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForEvent' : IDL.Func([IDL.Nat], [], []),
    'requestToJoin' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startConversation' : IDL.Func([IDL.Principal], [Conversation], []),
    'updateListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
    'uploadProfileImage' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };